
using Microsoft.AspNetCore.Mvc;
using HayvanatBahcesiProje.Models;
using System.Linq;
using System.Collections.Generic;

namespace HayvanatBahcesi.Controllers
{
    public class HomeController : Controller
    {
        private static List<Hayvan> Hayvanlar = new List<Hayvan>
        {
            // --- UÇAN HAYVANLAR ---
            new Hayvan { Id=1, Ad="Kelebek", Tur="Böcek", Ulke="Kolombiya", Omur="2 Hafta", Boy="3-10cm", Agirlik="100mg-500mg", ResimUrl="kelebek.jpg",Bilgi="Kelebekler, doğanın en narin ve renkli canlıları olarak bilinirler.Hayatlarına tırtıl olarak başlayıp muazzam bir dönüşümle kanatlanırlar.Hafif gövdeleri ve ipeksi kanatlarıyla çiçekten çiçeğe özgürce uçarlar.Dünya üzerinde binlerce farklı türü ve büyüleyici desenleri bulunur.Kısa ama etkileyici ömürleriyle doğadaki değişimin en güzel simgesidirler." },
            new Hayvan { Id=2, Ad="Papağan", Tur="Kuş", Ulke="Güney Amerika, Avustralya", Omur="25-30 yıl", Boy="30-35cm", Agirlik="30-400gram", ResimUrl="papa.jpg",Bilgi="Papağanlar, canlı renkleri ve yüksek zekalarıyla kuş dünyasının en dikkat çekici üyeleridir.Kıvrık gagaları ve güçlü ayaklarıyla yiyeceklerini bir el gibi kavrayıp yiyebilirler.İnsan seslerini ve çevredeki melodileri taklit etme yetenekleri oldukça gelişmiştir.Doğada çok sosyal canlılardır ve türlerine göre 80 yıla kadar yaşayabilirler.Sadık birer dost olmalarının yanı sıra karmaşık bulmacaları çözecek kadar zekidirler." },
            new Hayvan { Id=3, Ad="Sinek", Tur="Böcek", Ulke="Cezayir", Omur="15-30 gün", Boy="5-8mm", Agirlik="10-15 miligram", ResimUrl="sinek.jpg",Bilgi="Sinekler, çevik hareketleri ve hızlı kanat çırpışlarıyla bilinen küçük kanatlı böceklerdir.Karmaşık göz yapıları sayesinde çevrelerini geniş bir açıyla ve çok hızlı şekilde algılarlar.Duvarlarda ve tavanda ters yürümelerini sağlayan vantuz benzeri ayak yapılarına sahiptirler.Doğada organik atıkların ayrıştırılmasına yardımcı olarak önemli bir görev üstlenirler.Dünya üzerinde kutuplardan çöllere kadar hemen her türlü iklimde yaşayabilen dirençli canlılardır."},
            new Hayvan { Id=4, Ad="Albatros", Tur="Kuş", Ulke="Yeni Zelanda, Avustralya", Omur="50-60 yıl", Boy="3,5 metre", Agirlik="8-10kg", ResimUrl="alb.jpg",Bilgi="Albatroslar, kanat açıklığı üç metreyi aşabilen dünyanın en büyük uçan kuşlarından biridir.Aylarca hiç karaya ayak basmadan, okyanusların üzerinde binlerce kilometre yol kat edebilirler.Dinamik süzülme teknikleri sayesinde neredeyse hiç kanat çırpmadan rüzgâr yardımıyla uçarlar.Eşlerine son derece sadıktırlar ve genellikle ömür boyu süren güçlü bağlar kurarlar.Zamanlarının çoğunu açık denizlerde geçirip, sadece üremek için ıssız adalara iniş yaparlar." },
            new Hayvan { Id=5, Ad="Karga", Tur="Kuş", Ulke="Avustralya", Omur="10-15 yıl", Boy="40-70cm", Agirlik="300gram-1.5kg", ResimUrl="karga.jpg",Bilgi="Kargalar, yüksek zekaları ve problem çözme yetenekleriyle kuş dünyasının en akıllı üyeleridir.Yüzleri yıllarca unutmazlar ve kendilerine iyilik ya da kötülük yapanları hafızalarına kazırlar.Doğada buldukları araçları kullanarak dar yerlerdeki yiyeceklere ulaşma becerisine sahiptirler.Oldukça sosyal canlılardır ve tehlike anlarında birbirlerini uyarmak için karmaşık sesler çıkarırlar.Hem doğada hem de şehir hayatında her türlü yiyeceğe uyum sağlayabilen çok dayanıklı kuşlardır." },
            new Hayvan { Id=6, Ad="Pelikan", Tur="Kuş", Ulke="Yunanistan, Türkiye, Romanya", Omur="15-25 yıl", Boy="1.8 metre-3 metre", Agirlik="4kg-15kg", ResimUrl="pelikan.jpg",Bilgi="Pelikanlar, gagalarının altındaki devasa deri keseleriyle balık avlayan usta avcılardır.Geniş kanat açıklıkları sayesinde gökyüzünde büyük gruplar hâlinde süzülerek uçarlar.Avlarını yakalamak için bazen yüksekten suya hızla dalarak görkemli görüntüler oluştururlar.Hem tatlı sularda hem de deniz kıyılarında yaşayan oldukça sosyal ve uyumlu canlılardır.Yavrularını beslemek için yiyecekleri kursaklarında taşıyan fedakâr ebeveynlik özelliklerine sahiptirler."},
            new Hayvan { Id=7, Ad="Güve", Tur="Böcek", Ulke="Meksika", Omur="1-2 hafta", Boy="2mm-30cm", Agirlik="10mg-200mg", ResimUrl="guve.jpg",Bilgi="Güveler, genellikle gece aktif olan ve kelebeklere çok benzeyen zarif kanatlı böceklerdir.Kelebeklerin aksine dinlenirken kanatlarını çatı şeklinde vücutlarının üzerine kapatırlar.Tüylü antenleri sayesinde gece karanlığında koku moleküllerini çok hassas bir şekilde algılarlar.Doğada bitkilerin tozlaşmasına yardımcı olan gizli ama önemli kahramanlar arasındadırlar.Işık kaynaklarına olan düşkünlükleri ve desenli kanat yapılarıyla doğanın gizemli canlılarıdır." },
            new Hayvan { Id=8, Ad="Gökdoğan", Tur="Kuş", Ulke="Meksika", Omur="12-15 yıl", Boy="34-58cm", Agirlik="600gram-1kg", ResimUrl="gokdogan.jpg",Bilgi="Gökdoğanlar, saatte 320 kilometreyi aşan hızlarıyla dünyanın en hızlı hayvanı olarak bilinirler.Avlarını yakalamak için gökyüzünden yüksek hızla yaptıkları dikey dalışlar tam bir mühendislik harikasıdır.Keskin gözleri sayesinde kilometrelerce uzaktaki küçük bir kuşu bile kolayca fark edebilirler.Antarktika hariç dünyanın hemen her kıtasında, hatta modern şehirlerin gökdelenlerinde bile yaşarlar.Hızlarına rağmen havada inanılmaz manevra kabiliyetine sahip, doğanın en usta avcılarından biridirler." },
            new Hayvan { Id=9, Ad="Sinek Kuşu", Tur="Kuş", Ulke="Meksika", Omur="3-5 yıl", Boy="7-13cm", Agirlik="2-6gram", ResimUrl="sinekkusu.jpg",Bilgi="Sinek kuşları, saniyede 80 kez kanat çırparak havada asılı kalabilen dünyanın en küçük kuşlarıdır.Geriye doğru uçabilen tek kuş türü olup, çiçek özleriyle beslenirken havada sabit durabilirler.Kalpleri dakikada 1200 kez atacak kadar hızlı çalışan, inanılmaz bir enerjiye sahip canlılardır.Uzun ve ince gagaları ile fırça uçlu dilleri, en derin çiçeklerden bile besin almalarını sağlar.Işığı yansıtan metalik renkli tüyleri, hareket ettikçe parlayan bir mücevher gibi görünmelerine neden olur." },
            new Hayvan { Id=10, Ad="Güvercin", Tur="Kuş", Ulke="İtalya, Yunanistan, Türkiye, Mısır, Fas, İran", Omur="6-20 yıl", Boy="30cm", Agirlik="250gram", ResimUrl="guvercin.jpg",Bilgi="Güvercinler, yön bulma yetenekleri sayesinde binlerce kilometre öteden evlerini bulabilen usta gezginlerdir.Tarih boyunca insanlar arasında haberleşmeyi sağlayan sadık birer postacı olarak görev yapmışlardır.Şehir hayatına en iyi uyum sağlayan kuşlardan biri olup parklarda ve meydanlarda sürüler hâlinde yaşarlar.Yavrularını beslemek için 'kursak sütü' adı verilen özel bir sıvı üreten nadir kuş türlerinden biridirler.Barışın ve huzurun simgesi olarak kabul edilen bu kuşlar, dünya genelinde yüzlerce farklı türe sahiptir." },
            new Hayvan { Id=11, Ad="Bal Arısı", Tur="Eklembacaklı", Ulke="Slovenya", Omur="6 hafta-5 yıl", Boy="1.5cm", Agirlik="0.1gram", ResimUrl="BalArisi.jpg",Bilgi="Bal arıları, koloniler halinde yaşayan ve doğadaki bitkilerin tozlaşmasında hayati rol oynayan çalışkan böceklerdir.Hayatları boyunca çiçek çiçek gezerek topladıkları nektarı, kovanlarında mucizevi bir besin olan bala dönüştürürler.Kovan içerisinde kraliçe, işçi ve erkek arılar arasında mükemmel bir iş bölümü ve sosyal düzen vardır.Birbirleriyle 'arı dansı' denilen özel hareketlerle haberleşerek yiyecek kaynaklarının yerini tarif ederler.İnsanlar için sadece bal değil, balmumu, polen ve propolis gibi şifalı ürünler üreten doğanın en değerli canlılarındandırlar." },
            new Hayvan { Id=12, Ad="Leylek", Tur="Kuş", Ulke="Almanya", Omur="20-25 yıl", Boy="115cm", Agirlik="3-4.5 gram", ResimUrl="leylek.jpg",Bilgi="Leylekler, her yıl binlerce kilometre yol katederek mevsim değişimlerine göre göç eden gezgin kuşlardır.Genellikle evlerin çatılarına veya elektrik direklerinin tepelerine devasa çalı yuvalarını kurarlar.Halk arasında baharın müjdecisi olarak kabul edilir ve şans getirdiklerine inanılır.Beslenmek için sulak alanları tercih ederek kurbağa, balık ve küçük sürüngenleri avlarlar.Eşlerine bağlılıkları ve uzun bacaklı, zarif duruşlarıyla doğanın en sevilen silüetlerinden biridirler." },
            new Hayvan { Id=13, Ad="Yarasa", Tur="Memeli", Ulke="Romanya", Omur="15-20 yıl", Boy="3-10cm", Agirlik="5-30 gram", ResimUrl="yarasa.jpg",Bilgi="Yarasalar, uçma yeteneğine sahip olan tek memeli canlı türü olarak doğada benzersiz bir yere sahiptirler.Geceleri aktif olan bu canlılar, yaydıkları ses dalgalarının yankısıyla yollarını ve avlarını kolayca bulurlar.Tarım zararlılarını avlayarak ekosistemi korur ve bazı bitki türlerinin tozlaşmasına büyük katkı sağlarlar.Mağaralarda veya ağaç kovuklarında baş aşağı asılı durarak dinlenen oldukça sosyal hayvanlardır.Dünya üzerinde binden fazla türü bulunan yarasalar, sanılanın aksine görme yetisine de sahiptirler." },
            new Hayvan { Id=14, Ad="Yusufçuk", Tur="Böcek", Ulke="Japonya", Omur="6 ay-1 yıl", Boy="5-12cm", Agirlik="0.5-1 gram", ResimUrl="yusufcuk.jpg",Bilgi="Yusufçuklar, havada asılı kalabilen ve her yöne manevra yapabilen dünyanın en usta uçucularındandır.Dört kanadını birbirinden bağımsız hareket ettirerek helikopter benzeri inanılmaz bir uçuş sergilerler.Geniş ve karmaşık göz yapıları sayesinde çevrelerini neredeyse 360 derecelik bir açıyla görebilirler.Mükemmel birer avcıdırlar; havada uçan sinek ve küçük böcekleri yüksek bir başarı oranıyla yakalarlar.Su kenarlarında yaşayan bu canlılar, hem sudaki hem de karadaki ekosistemin dengesi için çok önemlidirler." },

            // --- YÜZEN HAYVANLAR ---
            new Hayvan { Id=15, Ad="Fok", Tur="Memeli", Ulke="Kanada, Kuzey Amerika", Omur="25-30 yıl", Boy="1.2 metre-6 metre", Agirlik="45kg-1 ton", ResimUrl="fok.jpg",Bilgi="Foklar, hem karada hem de suda yaşayabilen, sevimli ve tombul görünümlü memeli deniz canlılarıdır.Vücutlarındaki kalın yağ tabakası sayesinde dondurucu soğuklara karşı mükemmel bir koruma sağlarlar.Karada hantal hareket etseler de suyun altında harika birer yüzücü ve usta birer avcıdırlar.Uzun bıyıkları, suyun altındaki en küçük titreşimleri bile algılayarak avlarının yerini bulmalarına yardımcı olur.Sosyal hayvanlardır ve genellikle kıyılarda büyük gruplar hâlinde güneşlenirken veya dinlenirken görülürler." },
            new Hayvan { Id=16, Ad="Su Aygırı", Tur="Memeli", Ulke="Mısır", Omur="40-50 yıl", Boy="3,5-5 metre", Agirlik="1500kg-3000kg", ResimUrl="aygir.jpg",Bilgi="Su aygırları, devasa cüsselerine rağmen suyun altında oldukça çevik hareket edebilen yarı sucul memelilerdir.Günün büyük bir kısmını serinlemek için nehirlerde geçirir, geceleri ise otlamak için karaya çıkarlar.Gözleri, kulakları ve burun delikleri başlarının tepesinde olduğundan suyun altındayken bile çevreyi izleyebilirler.Kendi bölgelerini koruma konusunda son derece hassas ve doğadaki en güçlü çene yapılarından birine sahip canlılardır.Ciltlerini güneşten korumak için 'kan teri' denilen ve güneş kremi görevi gören kırmızımsı bir sıvı salgılarlar."},
            new Hayvan { Id=17, Ad="Yelken Balığı", Tur="Balık (İstingiller)", Ulke="Meksika", Omur="4-13 yıl", Boy="3 metre", Agirlik="50-100kg", ResimUrl="yelkenli.jpg",Bilgi="Yelken balıkları, suyun altında saatte 110 kilometreyi aşan hızlarıyla denizlerin en hızlı canlısı olarak bilinirler.Sırtlarında bulunan devasa yelken benzeri yüzgeçleri, avlanırken ani manevralar yapmalarına yardımcı olur.Üst çenelerinin uzantısı olan kılıç şeklindeki burunlarını, balık sürülerini dağıtmak ve avlarını sersemletmek için kullanırlar.Hızlandıklarında veya heyecanlandıklarında vücut renklerini değiştirerek avlarını şaşırtma yeteneğine sahiptirler.Okyanusların açık sularında yaşayan bu muazzam balıklar, sportif balıkçılık dünyasının en prestijli türlerinden biridir." },
            new Hayvan { Id=18, Ad="Marlin", Tur="Balık (İstingiller)", Ulke="Meksika", Omur="20-27 yıl", Boy="5 metre", Agirlik="700-800kg", ResimUrl="marlin.jpg",Bilgi="Marlinler, okyanusların en güçlü ve hızlı yüzücülerinden biri olup, mızrağımsı uzun üst çeneleriyle tanınırlar.Gövde yapıları sayesinde suyun direncini kırarak saatte yaklaşık 110 kilometre hıza kadar ulaşabilirler.Avlanırken mızraklarını balık sürülerini sersemletmek için kullanır ve inanılmaz bir çeviklik sergilerler.Oldukça büyük boyutlara ulaşabilen bu balıklar, suyun üzerinden metrelerce yükseğe sıçrama yeteneğine sahiptir.Açık denizlerin bu görkemli avcıları, dayanıklılıkları nedeniyle sportif balıkçılar için en büyük ödül sayılır." },
            new Hayvan { Id=19, Ad="Ördek", Tur="Kuş", Ulke="Çin", Omur="6-10 yıl", Boy="30-75cm", Agirlik="700gram-3kg", ResimUrl="ordek.jpg",Bilgi="Ördekler, hem suda hem de karada yaşayabilen, perdeli ayakları sayesinde usta birer yüzücü olan canlılardır.Su geçirmez tüyleri ve altlarındaki yoğun tüy tabakası, dondurucu sularda bile vücut ısılarını korumalarını sağlar.Geniş ve yassı gagalarıyla suyun içindeki bitkileri, böcekleri ve küçük canlıları süzerek beslenirler.Dünya genelinde hem evcil hem de yaban hayatında çok yaygın olan, sosyal ve neşeli kuş türleridir.Göçmen olan türleri, mevsim değişimlerinde binlerce kilometrelik yolculukları büyük sürüler halinde tamamlarlar."},
            new Hayvan { Id=20, Ad="Kaz", Tur="Kuş", Ulke="Rusya", Omur="15-20 yıl", Boy="1,5 metre", Agirlik="10-15kg", ResimUrl="kaz.jpg",Bilgi="Kazlar, hem karada hem de suda yaşamaya uyum sağlamış, güçlü ve dayanıklı gövde yapılarıyla bilinen iri kuşlardır.Vücutlarındaki yoğun ve su geçirmeyen tüyler, onları en soğuk havalarda ve dondurucu sularda bile sıcak tutar.Oldukça korumacı ve sadık canlılardır; tehlike anlarında kanatlarını açıp tıslayarak çevrelerini cesurca savunurlar.Göç ederken 'v' şeklinde uçarak hem enerji tasarrufu sağlar hem de grup içindeki iletişimi en üst düzeyde tutarlar.Otçul ağırlıklı beslenen bu canlılar, uzun ömürleri ve güçlü hafızalarıyla bilinen sosyal hayvan topluluklarıdır." },
            new Hayvan { Id=21, Ad="Deniz Aslanı", Tur="Memeli", Ulke="Kanada", Omur="20-30 yıl", Boy="1.5-3.3 metre", Agirlik="100kg-1 ton", ResimUrl="denizaslani.jpg",Bilgi="Deniz aslanları, kulak kepçeleri ve neşeli tavırlarıyla tanınan son derece zeki deniz memelileridir.Fokların aksine, uzun ön yüzgeçlerini kullanarak karada yürüyebilir ve su altında hızla yüzebilirler.Oldukça sosyal canlılardır; kayalık kıyılarda veya kumsallarda büyük, gürültülü koloniler halinde toplanırlar.Keskin duyuları ve çeviklikleri sayesinde balık, mürekkep balığı ve kabukluları avlayan usta avcılardır.Kendine has yüksek sesli havlamaları ve oyuncu hareketleriyle kıyı bölgelerinin en dikkat çekici sakinleridir." },
            new Hayvan { Id=24, Ad="Deniz Atı", Tur="Balık", Ulke="Avustralya", Omur="1-5 yıl", Boy="1,5-35cm", Agirlik="10-400 gram", ResimUrl="denizati.jpg",Bilgi="Deniz atları, kafaları bir atı andıran ve dik bir şekilde yüzen oldukça sıra dışı deniz canlılarıdır.Vücutlarını saran sert kemiksi plakalar, onları diğer balıklardan ayıran doğal bir zırh görevi görür.Kuyruklarını bitkilere veya mercanlara dolayarak, akıntılara rağmen sabit kalmayı başaran usta tutunuculardır.Doğada erkeklerin hamile kaldığı ve yavruları kendi keselerinde taşıdığı bilinen tek canlı türüdürler.Gözlerini birbirinden bağımsız hareket ettirebilme yetenekleri sayesinde çevrelerini her an takip edebilirler." },
            new Hayvan { Id=25, Ad="Hayalet Vatoz (Manta Vatozu)", Tur="Balık (Myliobatidae)", Ulke="Avustralya", Omur="40-50 yıl", Boy="7-9 metre", Agirlik="1-3 ton", ResimUrl="vatoz.jpg",Bilgi="Hayalet vatozlar, okyanusun derin ve karanlık sularında süzülen gizemli ve nadir görülen canlılardır.Vücutlarındaki biyolüminesans özellikleri sayesinde karanlıkta hafif bir ışık yayarak adeta bir hayalet gibi görünürler.Kanat benzeri geniş yüzgeçlerini ağır ağır çırparak suyun altında uçuyormuşçasına zarif bir hareket sergilerler.Derin denizlerin yüksek basıncına ve dondurucu soğuğuna uyum sağlamış oldukça dayanıklı bir yapıya sahiptirler.Göz kamaştırıcı ama bir o kadar da ürpertici güzellikleriyle deniz biyologları için hâlâ keşfedilmeyi bekleyen sırlar barındırırlar." },
            new Hayvan { Id=26, Ad="Katil Balina (Orka)", Tur="Balık (Yunusgiller)", Ulke="Japonya", Omur="30-80 yıl", Boy="6-10 metre", Agirlik="3-6 ton", ResimUrl="orka.jpg",Bilgi="Katil balinalar, isimlerinin aksine aslında okyanus yunusları ailesinin en iri üyeleridir.Kendilerine has siyah-beyaz renkleri ve devasa sırt yüzgeçleriyle okyanusların en kolay tanınan canlılarıdır.'Denizlerin Kurtları' olarak bilinirler çünkü sürüler hâlinde, stratejik ve son derece zekice avlanırlar.Yüksek zekaları sayesinde farklı avlanma teknikleri geliştirir ve bunları nesilden nesle aktarırlar.Besin zincirinin en üstünde yer alırlar ve doğada bilinen hiçbir doğal düşmanları yoktur." },
            new Hayvan { Id=27, Ad="Mantis Karidesi", Tur="Kabuklu", Ulke="Avustralya", Omur="3-20 yıl", Boy="10-30cm", Agirlik="100-600 gram", ResimUrl="mantis.jpg",Bilgi="Mantis karidesleri, doğadaki en güçlü ve en hızlı vuruş yeteneğine sahip canlılardan biri olarak bilinirler.Özel kıskaçlarıyla bir mermiden daha hızlı vuruşlar yaparak avlarının kabuklarını veya akvaryum camlarını kırabilirler.Gözleri, insanların göremediği ultraviyole ve polarize ışığı algılayabilen, dünyadaki en karmaşık görme sistemine sahiptir.Vücutlarındaki göz kamaştırıcı ve canlı renkler, onlara suyun altında bir mücevher gibi dikkat çekici bir görünüm kazandırır.Yalnız yaşamayı seven bu agresif avcılar, mercan resiflerindeki yuvalarını diğer canlılara karşı cesurca savunurlar." },
            new Hayvan { Id=28, Ad="Güneş Balığı (Mola Mola)", Tur="Balık", Ulke="İtalya", Omur="10 yıl", Boy="3-4 metre", Agirlik="1000kg-2300kg", ResimUrl="mola.jpg",Bilgi="Güneş balıkları, dünyanın en ağır kemikli balığı olup yandan basık ve devasa bir tabağı andıran garip bir gövdeye sahiptir.Yüzgeçleri hariç kuyruğu yokmuş gibi görünen bu canlılar, okyanus yüzeyinde yan yatarak güneşlenmeyi çok severler.Sırt ve anal yüzgeçlerini aynı anda çırparak suyun altında oldukça yavaş ama kararlı bir şekilde ilerlerler.Temel besin kaynakları olan deniz analarını tüketerek okyanus ekosisteminin dengelenmesine yardımcı olurlar.Tek bir seferde 300 milyona kadar yumurta bırakabilen, üreme kapasitesi en yüksek omurgalı canlılardan biridirler." },
            new Hayvan { Id=29, Ad="Salp", Tur="Omurgalı (Tunikatlar)", Ulke="Yeni Zelanda", Omur="Birkaç hafta-3 ay", Boy="1-15cm", Agirlik="10-15 miligram", ResimUrl="salp.jpg",Bilgi="Salplar, okyanuslarda yaşayan, vücutları tamamen şeffaf ve jelatinimsi bir yapıya sahip olan ilginç deniz canlılarıdır.Suyu vücutlarından pompalayarak hem hareket ederler hem de içindeki mikroskobik planktonları süzerek beslenirler.Bazen uç uca eklenerek metrelerce uzunlukta, parlak ve muazzam zincirler oluşturan sosyal koloniler kurarlar.Atmosferdeki karbondioksiti emip dışkılarıyla okyanus tabanına ileterek iklim krizini yavaşlatmaya yardımcı olurlar.Karmaşık bir yaşam döngüsüne sahiptirler ve uygun koşullarda inanılmaz bir hızla çoğalarak devasa sürüler oluşturabilirler." },
            new Hayvan { Id=30, Ad="Yeşil Deniz Kaplumbağası (Caretta Caretta)", Tur="Sürüngen", Ulke="Türkiye", Omur="70-80 yıl", Boy="80-120cm", Agirlik="150kg-300kg", ResimUrl="kaplumbaga.jpg",Bilgi="Yeşil deniz kaplumbağaları, adlarını derilerinin altındaki yağ tabakasının renginden alan devasa deniz gezginleridir.Yumurtadan çıktıktan sonra okyanusun derinliklerine ulaşmak için ay ışığını takip ederek zorlu bir yolculuğa çıkarlar.Erişkinlik dönemlerinde çoğunlukla deniz çayırları ve alglerle beslenerek deniz ekosisteminin bahçıvanlığını yaparlar.Yumurtlamak için her zaman doğdukları kumsala geri dönen, inanılmaz bir yön bulma ve sadakat yeteneğine sahiptirler.Yüzyılı aşkın süre yaşayabilen bu canlılar, okyanusların en eski ve en saygın sakinleri arasında kabul edilirler." },
            new Hayvan { Id=31, Ad="Beyaz Köpekbalığı", Tur="Kıkırdaklı Balık", Ulke="Avustralya", Omur="70 yıl", Boy="4.5-6 metre", Agirlik="1000-2000kg", ResimUrl="kopekbaligi.jpg",Bilgi="Büyük beyaz köpekbalıkları, okyanusların en güçlü ve en çok merak edilen yırtıcılarının başında gelirler.Torpidoyu andıran aerodinamik gövdeleri sayesinde suyun altında çok yüksek hızlara ve çevikliğe ulaşırlar.Ağızlarında bulunan yüzlerce testere dişli keskin diş, kayboldukça sürekli yenilenen bir yapıya sahiptir.Sudaki çok küçük kan damlalarını veya titreşimleri kilometrelerce öteden algılayabilen kusursuz duyuları vardır.Okyanus ekosisteminde besin zincirinin en üstünde yer alarak deniz yaşamının dengesini korumada kritik rol oynarlar." },
            new Hayvan { Id=32, Ad="Su Samuru", Tur="Memeli", Ulke="Kanada", Omur="10-15 yıl", Boy="100-120cm", Agirlik="10-25kg", ResimUrl="susamuru.jpg",Bilgi="Su samurları, hem tatlı sularda hem de deniz kıyılarında yaşayan, son derece oyuncu ve zeki memelilerdir.Su geçirmez ve çok yoğun tüy yapıları, dondurucu sularda bile vücut ısılarını mükemmel şekilde korur.Yemek yerken veya dinlenirken suyun üzerinde sırtüstü yatar ve akıntıya kapılmamak için birbirlerinin elini tutarlar.En sevdikleri yiyecek olan deniz kabuklularını kırmak için taş kullanan, alet yapabilen nadir hayvanlardandır.Enerjik yapıları ve suda sergiledikleri akrobatik hareketlerle doğanın en sempatik canlıları arasında yer alırlar." },
            new Hayvan { Id=33, Ad="Mavi Balina", Tur="Memeli", Ulke="İzlanda", Omur="80-90 yıl", Boy="25-30 metre", Agirlik="150-190 ton", ResimUrl="mavibalina.jpg",Bilgi="Mavi balinalar, 30 metreye ulaşan boylarıyla dünya üzerinde yaşamış olan en büyük hayvanlardır.Sadece dillerinin ağırlığı bir fil kadar, kalpleri ise bir otomobil büyüklüğündedir.Okyanusun derinliklerinde çıkardıkları sesler, yüzlerce kilometre öteden duyulabilen en yüksek sesli canlılardır.Devasa cüsselerine rağmen sadece kril adı verilen mikroskobik deniz canlılarını süzerek beslenirler.Nadir görülen bu görkemli devler, okyanus ekosisteminin dengesi için hayati bir öneme sahiptirler." },
            new Hayvan { Id=34, Ad="Ahtapot", Tur="Yumuşakça", Ulke="Yunanistan", Omur="1-2 yıl", Boy="60-90cm", Agirlik="3-10kg", ResimUrl="octopus.jpg",Bilgi="Ahtapotlar, sekiz kolları ve dokuz beyinleri olan dünyanın en zeki omurgasız canlılarıdır.Vücutlarında kemik bulunmadığı için en dar boşluklardan bile kolayca süzülerek geçebilirler.Derilerinin rengini ve dokusunu saniyeler içinde değiştirerek bulundukları ortama mükemmel uyum sağlarlar.Tehlike anlarında düşmanlarını şaşırtmak için suya koyu renkli bir mürekkep püskürterek uzaklaşırlar.Problem çözme, labirentleri aşma ve kavanoz kapaklarını açma gibi şaşırtıcı zihinsel yeteneklere sahiptirler." },

            // --- KOŞAN HAYVANLAR ---
            new Hayvan { Id=35, Ad="Deve Kuşu", Tur="Kuş", Ulke="Etiyopya", Omur="40-45 yıl", Boy="2.1-2.8 metre", Agirlik="100-150kg", ResimUrl="deveusu.jpg",Bilgi="Deve kuşları, dünyanın en büyük ve en ağır kuş türü olup uçamayan canlılar kategorisindedirler.Güçlü ve uzun bacakları sayesinde saatte 70 kilometre hıza ulaşabilen dünyanın en hızlı koşan kuşlarıdır.Gözleri, beyinlerinden daha büyüktür ve bu sayede uçsuz buçaksız arazilerdeki tehlikeleri uzaktan fark ederler.Sanılanın aksine korktuklarında kafalarını kuma gömmezler; sadece kendilerini gizlemek için yere uzanırlar.Devasa yumurtaları, yaklaşık iki düzine tavuk yumurtasına eşdeğer büyüklükte olup dünyanın en büyük yumurtasıdır." },
            new Hayvan { Id=36, Ad="Leopar", Tur="Memeliler (Kedigiller)", Ulke="Etiyopya", Omur="12-15 yıl", Boy="2 metre", Agirlik="60-90kg", ResimUrl="leop.jpg",Bilgi="Leoparlar, benekli kürkleri ve muazzam güçleriyle kedigiller ailesinin en çevik ve usta avcılarından biridir.Vücut ağırlıklarının iki katı büyüklükteki avlarını bile korumak için ağaçların yüksek dallarına taşıyabilirler.Dünya üzerinde ormanlardan çöllere kadar en geniş coğrafi alana yayılabilen, uyum yeteneği en yüksek yırtıcıdırlar.Mükemmel kamuflaj yetenekleri ve sessiz hareket etme becerileri sayesinde 'gecenin hayaleti' olarak anılırlar.Diğer büyük kedilerin aksine hem çok iyi birer tırmanıcı hem de suya girmekten çekinmeyen usta yüzücülerdir." },
            new Hayvan { Id=37, Ad="Tilki", Tur="Memeliler (Köpekgiller)", Ulke="Kuzey Amerika", Omur="2-12 yıl", Boy="60-90cm", Agirlik="5-10kg", ResimUrl="tilki.jpg",Bilgi="Tilkiler, keskin zekaları ve kurnazlıklarıyla tanınan, köpek ailesinin en çevik üyeleridir.Kuyruklarını hem dengelerini sağlamak hem de soğuk havalarda ısınmak için bir battaniye gibi kullanırlar.Dünyanın hemen her yerinde, şehirlerden kutuplara kadar farklı iklim koşullarına uyum sağlayabilirler.Çok gelişmiş duyma yetenekleri sayesinde karın altındaki farelerin hareketlerini bile kolayca tespit ederler.Yalnız avlanmayı tercih eden bu canlılar, doğanın dengesini koruyan usta ve esnek avcılar arasındadır." },
            new Hayvan { Id=38, Ad="Sırtlan", Tur="Memeli", Ulke="Fransa", Omur="12-15 yıl", Boy="1-1.6m", Agirlik="45-80kg", ResimUrl="sirtlan.jpg",Bilgi="Sırtlanlar, doğadaki en güçlü çene yapılarından birine sahip olan, son derece dayanıklı yırtıcılardır.Sanılanın aksine sadece leşçil değillerdir; kendi avlarını sürü hâlinde büyük bir ustalıkla avlarlar.Yüksek zekaları ve karmaşık sosyal yapıları sayesinde, kendi aralarında organize bir hiyerarşi kurarlar.İnsan gülüşüne benzeyen kendilerine has sesleri, aslında sürülerindeki iletişim ve heyecanı yansıtır.Avladıkları hayvanların kemiklerini bile tamamen sindirebilen sindirim sistemleri ile ekosistemin temizleyicileridirler." },
            new Hayvan { Id=39, Ad="Çakal", Tur="Memeli (Köpekgiller)", Ulke="Amerika", Omur="8-15 yıl", Boy="70-85cm", Agirlik="7-15kg", ResimUrl="cakal.jpg",Bilgi="Çakallar, kurnazlıkları ve yüksek uyum yetenekleriyle tanınan, köpek ailesinin orta boylu üyeleridir.Genellikle akşam karanlığında ve gece aktifleşerek kendilerine has ulumalarıyla birbirleriyle haberleşirler.Hem iyi birer avcı hem de fırsatçı leşçil olduklarından, ekosistemin temizlenmesinde önemli rol oynarlar.Çoğunlukla tek eşli bir yaşam sürerler ve yavrularını büyütürken aile üyeleriyle yardımlaşırlar.Doğadan yerleşim yerlerine kadar çok geniş bir alanda hayatta kalabilen, son derece dirençli canlılardır." },
            new Hayvan { Id=40, Ad="Tazı", Tur="Memeli (Köpekgiller)", Ulke="Mısır", Omur="10-14 yıl", Boy="60-75cm", Agirlik="25-40kg", ResimUrl="tazi.jpg",Bilgi="Tazılar, atletik vücut yapıları ve ince bacaklarıyla dünyanın en hızlı koşan köpek ırklarından biridir.Görerek avlanma yetenekleri o kadar gelişmiştir ki, hareket eden avlarını çok uzak mesafelerden fark ederler.Aerodinamik gövdeleri ve geniş ciğer kapasiteleri, onlara kısa sürede inanılmaz hızlara çıkma imkanı tanır.Ev ortamında sanılanın aksine oldukça sakin, uysal ve günün büyük kısmını uyuyarak geçiren canlılardır.Tarih boyunca soyluların yanında av arkadaşı olarak yer almış, zarif duruşlarıyla bilinen sadık dostlardır." },
            new Hayvan { Id=41, Ad="Aslan", Tur="Memeli (Kedigiller)", Ulke="Etiyopya", Omur="10-16 yıl", Boy="3 metre", Agirlik="120-230kg", ResimUrl="aslan.jpg",Bilgi="Aslanlar, 'ormanların kralı' olarak bilinen ve kedigiller ailesinin sosyal bir yapıya sahip tek üyesidir.Gurur adı verilen sürüler halinde yaşayarak, doğadaki en organize avcı gruplarından birini oluştururlar.Erkek aslanların heybetli yeleleri, hem kendilerini korumalarını sağlar hem de bir güç göstergesidir.Kükremeleri o kadar güçlüdür ki, yaklaşık sekiz kilometre mesafeden bile kolayca duyulabilir.Günün büyük bir bölümünü dinlenerek geçirseler de, gece çöktüğünde son derece çevik yırtıcılara dönüşürler." },
            new Hayvan { Id=42, Ad="Çita", Tur="Memeli (Kedigiller)", Ulke="Namibya", Omur="10-12 yıl", Boy="110-150cm", Agirlik="35-65kg", ResimUrl="cita.jpg",Bilgi="Çitalar, saatte 110 kilometreyi aşan hızlarıyla dünyanın en hızlı kara hayvanı unvanına sahiptirler.Esnek omurgaları ve geniş adımları, sadece birkaç saniye içinde inanılmaz bir hıza ulaşmalarını sağlar.Denge sağlamak için kullandıkları uzun kuyrukları, yüksek hızda keskin manevralar yapmalarına yardımcı olur.Gözlerinin altındaki siyah 'gözyaşı' çizgileri, güneş ışığını kırarak avlarını daha net görmelerini sağlar.Diğer büyük kedilerin aksine kükreyemezler; ancak kuş sesine benzer cıvıltılar çıkararak iletişim kurarlar." },
            new Hayvan { Id=43, Ad="Afrika Fili", Tur="Memeli", Ulke="Botsvana", Omur="60-70 yıl", Boy="3-4 metre", Agirlik="4000-6000kg", ResimUrl="afrikafil.jpg",Bilgi="Afrika filleri, devasa kulakları ve uzun hortumlarıyla dünya üzerindeki en büyük kara memelileridir.Zeki ve duygusal canlılar olup, aile üyelerine sadakatleri ve güçlü hafızalarıyla tanınırlar.Hortumlarını hem nefes almak hem de bir el gibi nesneleri kavramak için büyük bir ustalıkla kullanırlar.Günde yüzlerce kilo bitki tüketerek ekosistemin şekillenmesinde 'doğa mühendisi' rolü üstlenirler.Vücut ısılarını devasa kulaklarını yelpaze gibi sallayarak dengeler ve serin kalmayı başarırlar." },
            new Hayvan { Id=44, Ad="Kanguru (Kızıl Kanguru)", Tur="Memeli (Keseli)", Ulke="Avustralya", Omur="12-20 yıl", Boy="1.5-2 metre", Agirlik="50-90kg", ResimUrl="kanguru.jpg",Bilgi="Kangurular, güçlü arka bacakları sayesinde çok uzak mesafelere zıplayarak yol alabilen sıra dışı canlılardır.Yavrularını, gelişimlerini tamamlayana kadar karınlarında bulunan güvenli bir kesede taşırlar.Zıplarken denge sağlamak için kullandıkları kaslı kuyrukları, adeta üçüncü bir bacak görevi görür.Sadece Avustralya kıtasına özgü olan bu memeliler, otçul beslenen ve sürüler halinde yaşayan sosyal hayvanlardır.Geriye doğru yürüyemeyen nadir canlılardan biri olmaları, onları fiziksel olarak benzersiz kılar." },
            new Hayvan { Id=45, Ad="Zürafa", Tur="Memeli", Ulke="Kenya", Omur="20-25 yıl", Boy="4.5-6 metre", Agirlik="800-1200kg", ResimUrl="zurafa.jpg",Bilgi="Zürafalar, altı metreye ulaşan boylarıyla dünyanın en uzun kara hayvanlarıdır.Uzun boyunları sayesinde diğer canlıların erişemediği yüksek dallardaki taze yapraklarla beslenirler.Yarım metreyi bulan morumsu dilleri, dikenli dallardan zarar görmeden yemek yemelerini sağlayan sert bir yapıdadır.Vücutlarındaki her bir benek deseni, tıpkı insan parmak izi gibi sadece o bireye özgüdür.Kalpleri, kanı o kadar yüksekten başlarına kadar pompalayabilmek için oldukça güçlü ve büyüktür." },
            new Hayvan { Id=46, Ad="Boz Ayı", Tur="Memeli", Ulke="Rusya", Omur="20-25 yıl", Boy="2-2.5 metre", Agirlik="150-600kg", ResimUrl="ayi.jpg",Bilgi="Boz ayılar, devasa cüsseleri ve omuzlarındaki belirgin kas tümsekleriyle doğanın en güçlü üyelerindendir.Hem bitki hem de etle beslenen bu canlılar, mevsimine göre meyvelerden somon balıklarına kadar geniş bir diyet uygularlar.Kış aylarını enerji tasarrufu sağlamak için derin bir uyku halini andıran kış uykusuna yatarak geçirirler.Pençeleri ve koku alma duyuları o kadar gelişmiştir ki, kilometrelerce ötedeki yiyecekleri kolayca bulabilirler.Yavrularına karşı son derece korumacı olan bu dev canlılar, ekosistemin dengesi için hayati bir önem taşırlar." },

            // --- ZIPLAYAN HAYVANLAR ---
            new Hayvan { Id=47, Ad="Kurbağa (Boğa Kurbağası)", Tur="Amfibi", Ulke="ABD", Omur="7-10 yıl", Boy="10-20cm", Agirlik="0.5-1kg", ResimUrl="kur.jpg",Bilgi="Kurbağalar, hem suda hem de karada yaşayabilen nemli ciltli ve zıplayan amfibilerdir.Yaşamlarına suda solungaçlı birer iribaş olarak başlayıp, sonra akciğerli yetişkinlere dönüşürler.Güçlü arka bacakları sayesinde boylarının kat kat fazlası mesafeye çevikçe zıplayabilirler.Yapışkan ve uzun dillerini bir kamçı gibi kullanarak uçan böcekleri hızla avlarlar.Derileri üzerinden nefes alabildikleri için çevre kirliliğine karşı oldukça hassas canlılardır." },
            new Hayvan { Id=48, Ad="Tavşan (Avrupa Tavşanı)", Tur="Memeli", Ulke="İspanya", Omur="5-9 yıl", Boy="30-50cm", Agirlik="1.5-2kg", ResimUrl="tavsan.jpg",Bilgi="Tavşanlar, uzun kulakları ve güçlü arka bacaklarıyla tanınan son derece hızlı ve çevik canlılardır.Tehlikeyi çok uzak mesafelerden duyabilen hassas kulakları, aynı zamanda vücut ısılarını dengeler.Sürekli büyüyen ön dişlerini törpülemek için gün boyu sert bitkiler ve köklerle beslenirler.Gözlerinin yanlarda olması sayesinde arkalarını bile görebilecek geniş bir görüş açısına sahiptirler.Toprağın altına kazdıkları karmaşık tünel sistemlerinde yaşayan, oldukça sosyal ve ürkek hayvanlardır." },
            new Hayvan { Id=49, Ad="Çekirge", Tur="Böcek", Ulke="Mısır", Omur="3-5 ay", Boy="1-10cm", Agirlik="2-3 gram", ResimUrl="cekirge.jpg",Bilgi="Çekirgeler, arka bacaklarındaki güçlü kaslar sayesinde kendi vücut uzunluklarının kat kat ötesine zıplayabilirler.Arka bacaklarını birbirine veya kanatlarına sürterek çıkardıkları kendilerine has seslerle iletişim kurarlar.Tarım alanlarında büyük sürüler hâlinde hareket ederek bitki örtüsü üzerinde önemli bir etkiye sahip olabilirler.Dünya genelinde binlerce türü bulunan bu böcekler, farklı iklim ve çevre koşullarına mükemmel uyum sağlarlar.Düz kanatlılar takımına ait olan bu canlılar, doğadaki besin zincirinin temel halkalarından birini oluştururlar." },
            new Hayvan { Id=50, Ad="İmpala", Tur="Memeli (Antilop)", Ulke="Güney Afrika", Omur="12-15 yıl", Boy="70-95cm", Agirlik="40-75kg", ResimUrl="impala.jpg",Bilgi="İmpalalar, zarif yapıları ve muazzam zıplama yetenekleriyle Afrika savanlarının en dikkat çekici antiloplarıdır.Tehlike anında 3 metre yüksekliğe ve 10 metre uzağa sıçrayarak yırtıcıların kafasını karıştırabilirler.Kızılımsı kahverengi kürkleri ve arka bacaklarındaki siyah çizgilerle doğada kolayca ayırt edilirler.Sürüler halinde yaşayan bu sosyal canlılar, çevrelerindeki her türlü değişikliğe karşı son derece tetiktedirler.Sadece erkeklerde bulunan liral şeklindeki uzun ve boğumlu boynuzları, onlara asil bir görünüm kazandırır." },
            new Hayvan { Id=51, Ad="Zıplayan Örümcek", Tur="Eklembacaklı", Ulke="Meksika", Omur="1-2 yıl", Boy="13-20mm", Agirlik="1 gramdan az", ResimUrl="ziplayan.jpg",Bilgi="Zıplayan örümcekler, kendi vücut uzunluklarının 50 katı mesafeye sıçrayabilen doğanın en çevik avcılarıdır.Sekiz gözlü karmaşık yapıları sayesinde, çevreyi yüksek çözünürlüklü ve üç boyutlu olarak mükemmel görürler.Diğer örümceklerin aksine ağ kurup beklemek yerine, avlarının üzerine aktif bir şekilde atlayarak saldırırlar.Sıçramadan önce kendilerini ipeksi bir ağla bir yere bağlayarak düşme riskine karşı güvenlik halatı oluştururlar.Küçük boyutlarına rağmen oldukça zeki olan bu canlılar, meraklı tavırları ve renkli danslarıyla bilinirler." },

            // --- SÜRÜNGEN HAYVANLAR ---
            new Hayvan { Id=52, Ad="Komodo Ejderi", Tur="Sürüngen", Ulke="Endonezya", Omur="30 yıl", Boy="2.5-3 metre", Agirlik="70-90kg", ResimUrl="komodo.jpg",Bilgi="Komodo ejderleri, boyları 3 metreye ulaşabilen dünyanın yaşayan en büyük kertenkele türüdür.Sadece Endonezya'nın birkaç adasında yaşayan bu dev sürüngenler, adeta birer tarih öncesi canlıyı andırırlar.Avlarını ısırırken kanın pıhtılaşmasını engelleyen zehirli bir salgı kullanarak etkisiz hale getirirler.Çatallı dilleriyle havadaki koku taneciklerini toplayarak kilometrelerce ötedeki bir avı bile kolayca bulabilirler.Güçlü kuyrukları ve zırhlı derileriyle ekosistemlerinin en tepesinde yer alan, rakipsiz birer avcıdırlar." },
            new Hayvan { Id=53, Ad="Kral Kobra", Tur="Sürüngen", Ulke="Hindistan", Omur="20 yıl", Boy="3-5.5 metre", Agirlik="6-10kg", ResimUrl="kobra.jpg",Bilgi="Kral kobralar, 5 metreyi aşabilen boylarıyla dünyanın en uzun zehirli yılanı olma unvanına sahiptirler.Tehlike hissettiklerinde vücutlarının ön kısmını havaya kaldırıp boyunlarını genişleterek heybetli bir duruş sergilerler.İsimlerinin hakkını vererek temel olarak diğer yılan türleriyle beslenen, kendi türünün en güçlü avcılarından biridirler.Doğada kendi yumurtaları için yuva yapan ve yavruları çıkana kadar onları koruyan tek yılan türüdürler.Tek bir ısırıkta salgıladıkları yoğun zehir miktarı, bir fili bile kısa sürede saf dışı bırakabilecek kadar güçlüdür." },
            new Hayvan { Id=54, Ad="Nil Timsahı", Tur="Sürüngen", Ulke="Mısır", Omur="70-100 yıl", Boy="4-6 metre", Agirlik="250-750kg", ResimUrl="nil.jpg",Bilgi="Nil timsahları, Afrika'nın nehirlerinde yaşayan ve boyları 6 metreye kadar ulaşabilen devasa sürüngenlerdir.Pusuda bekleme ustası olan bu canlılar, su kenarına gelen avlarını inanılmaz bir hızla yakalayıp suya çekerler.Doğadaki en güçlü ısırma kuvvetine sahip hayvanlardan biri olarak, en sert kemikleri bile kolayca kırabilirler.Vücut ısılarını dengelemek için gün boyu kıyılarda ağızları açık bir şekilde güneşlenerek dinlenirler.Yavrularını ağızlarında taşıyarak suya ulaştıran, sürüngenler dünyasının en korumacı ebeveynlerinden biridirler." },
            new Hayvan { Id=55, Ad="Bukalemun", Tur="Sürüngen", Ulke="Madagaskar", Omur="5-10 yıl", Boy="15-60cm", Agirlik="50-500 gram", ResimUrl="buke.jpg",Bilgi="Bukalemunlar, bulundukları ortama uyum sağlamak için renk değiştirebilen doğanın en yetenekli kamuflaj ustalarıdır.Birbirinden bağımsız hareket edebilen gözleri sayesinde, vücutlarını oynatmadan çevrelerini 360 derece izleyebilirler.Kendi vücut uzunluklarından daha uzun olan yapışkan dillerini hızla fırlatarak avlarını saniyeler içinde yakalarlar.Ayaklarının kıskaç benzeri yapısı ve güçlü kuyrukları, ağaç dallarına sıkıca tutunarak güvenle hareket etmelerini sağlar.Genellikle yavaş hareket eden bu sakin canlılar, hem kendilerini korumak hem de duygularını ifade etmek için renk değiştirirler." },
            new Hayvan { Id=56, Ad="Yeşil İguana", Tur="Sürüngen", Ulke="Meksika", Omur="15-20 yıl", Boy="1.2-1.7 metre", Agirlik="4-9kg", ResimUrl="yeigu.jpg",Bilgi="Yeşil iguanalar, Orta ve Güney Amerika'nın tropikal ormanlarında yaşayan en büyük kertenkele türlerinden biridir.Ağaçların tepelerinde yaşamayı severler ve güçlü pençeleri sayesinde dallara mükemmel şekilde tutunurlar.Çoğunlukla otçul beslenen bu canlılar; taze yapraklar, çiçekler ve meyvelerle beslenmeyi tercih ederler.Tehlike anlarında uzun ve güçlü kuyruklarını bir kırbaç gibi kullanarak kendilerini düşmanlara karşı savunurlar.Su kenarlarında yaşamaktan keyif alırlar ve herhangi bir tehdit hissettiklerinde yüksekten suya atlayarak hızla uzaklaşabilirler." }
        };

        public IActionResult Index(string arama, string sirala)
        {
            var sorgu = Hayvanlar.AsQueryable();

            if (!string.IsNullOrWhiteSpace(arama))
            {
                string kelime = arama.Trim().ToLower();
                sorgu = sorgu.Where(h => h.Ad.ToLower().Contains(kelime) ||
                                         h.Tur.ToLower().Contains(kelime) ||
                                         h.Ulke.ToLower().Contains(kelime));
            }

            sorgu = sirala switch
            {
                "tur" => sorgu.OrderBy(h => h.Tur),
                "ulke" => sorgu.OrderBy(h => h.Ulke),
                "omur" => sorgu.OrderBy(h => h.Omur),
                "boy" => sorgu.OrderBy(h => h.Boy),
                "agirlik" => sorgu.OrderBy(h => h.Agirlik),
                _ => sorgu.OrderBy(h => h.Ad)
            };

            return View(sorgu.ToList());
        }

        public IActionResult Giris()
        {
            return View();
        }

        public IActionResult detaylar(int id)
        {
            var hayvan = Hayvanlar.FirstOrDefault(x => x.Id == id);

            if (hayvan == null)
            {
                return RedirectToAction("Index");
            }

            return View(hayvan);
        }

        public IActionResult Sil(int id)
        {
            var hayvan = Hayvanlar.FirstOrDefault(x => x.Id == id);
            if (hayvan != null)
            {
                Hayvanlar.Remove(hayvan);
            }
            return RedirectToAction("Index");
        }
    }
}